[mypy]
mypy_path = $MYPY_CONFIG_FILE_DIR/modules
cache_dir = $MYPY_CONFIG_FILE_DIR/.mypy_cache

packages = venvcache,tulila,tulila_server
exclude = (rsrc/.*$)

strict = True

disallow_any_unimported = True
disallow_any_expr = True
disallow_any_decorated = True

warn_unreachable = True

[mypy-tulila._simulation._request_parsing]
allow_any_expr = True

[mypy-tulila._loader]
allow_any_expr = True
